### ISSUE TITLE
Question Model backend

### ISSUE THREAD

**Issue by jonthemango** [Kerry-G/Ask-Eng#11]
SQL model for Questions. 

createQuestion() 
updateQuestion() 
deleteQuestion() 
getQuestionsByUser() 
getQuestionsByEngineering()

**Comment by jonthemango** [comment]
id
title
text
ups
downs
engineer
user_id
closed (bool)
register_date

**Comment by Megan-VanHumbeck** [comment]
What should the branch for this be called?

**Comment by ramzouza** [comment]
This feature was finished by the back-end team.
