### ISSUE TITLE
Answer Model backend

### ISSUE THREAD

**Issue by jonthemango** [Kerry-G/Ask-Eng#13]
SQL model for Answers
getAnwsersByUser()
getAnwserByQuestion()
modifyAnwser()
createAnwser()
deleteAnwser()
verifyAnwser()

**Comment by jonthemango** [comment]
Answer Model:
id
text
ups
downs
user_id
question_id
accepted (bool)
register_date

**Comment by Kerry-G** [comment]
@jonthemango I think there is an error in your API, you may have broke it. When I try to save a question. it returns me:
```
   for answer in Answers.getAnswerByQuestion(question['id']):
AttributeError: module 'application.models.Answers' has no attribute 'getAnswerByQuestion'
```

when I try to send: 

`{title: "Title", text: "2", engineer: "Computer", user_id: 20}`

can you please have a look at that

**Comment by ramzouza** [comment]
This feature was completed by the back-end team.
