### ISSUE TITLE
Fix up Q/A page

### ISSUE THREAD

**Issue by jonthemango** [Kerry-G/Ask-Eng#26]
Needs better CSS. Comments should load as soon as you answer. Similarly, questions should load as soon as they are asked. Upvote/Downvote capbility on Q and A page.

**Comment by Kerry-G** [comment]
I started a branch called vote-component#-26 to work on the Upvote/Downvote capbility on Q and A page.

**Comment by JamalG16** [comment]
Created a branch called update-after-asking-or-answering#26 to work on the loading of answers/questions as soon as they are submitted.

**Comment by JamalG16** [comment]
Questions and answers load immediately after submitting without needing to reload the page. However, the submit button only works after one click. If the user wishes to submit multiple questions or answers, the user will have to refresh the page before submitting another.

**Comment by ramzouza** [comment]
@JamalG16 is this still an issue

**Comment by JamalG16** [comment]
@ramzouza Completed for last sprint, just forgot to close it
