### ISSUE TITLE
Mobile Responsive CSS

### ISSUE THREAD

**Issue by jonthemango** [Kerry-G/Ask-Eng#28]
Add CSS styles to make the app work perfectly on Mobile and Desktop devices.

**Comment by sharon-ho** [comment]
Made everything mobile friendly/responsive, except for the search bar. Will do that later.

**Comment by sharon-ho** [comment]
#45 Done

**Comment by sharon-ho** [comment]
#45 Done once merged

**Comment by sharon-ho** [comment]
#45 Done

**Comment by sharon-ho** [comment]
Actually, I will make the search into a dropdown for it to be more mobile friendly. Currently working on it.
