### ISSUE TITLE
Symbols in question title prevents question from submitting

### ISSUE THREAD

**Issue by sharon-ho** [Kerry-G/Ask-Eng#42]
When apostrophes or symbols (e.g. ?, ', etc.) are in the question's title, the question is not submitted to the database despite the "Submit Question" button being clickable.

**Comment by ramzouza** [comment]
We figured out the issue this is a back end issues and only occurs when apostrophe are used (') commas and interrogation point have no effect (?,)

**Comment by jonthemango** [comment]
Fixed bug.
