### ISSUE TITLE
Ups and downs on user's profile card are always returned as 0

### ISSUE THREAD

**Issue by sharon-ho** [Kerry-G/Ask-Eng#43]
When viewing user's profile page/card, the ups and downs are both zero. It should instead reflect the amount of upvotes and downvotes received in total by the user.

**Comment by jonthemango** [comment]
Bug has been fixed. It was a front end issue.

**Comment by jonthemango** [comment]
Apparently it was not yet fixed. Kerry will fix.

**Comment by Kerry-G** [comment]
I found out what the bug was. It is only happening on your own profile since the user informations isn't updated.
