### ISSUE TITLE
Create a website logo

### ISSUE THREAD

**Issue by ramzouza** [Kerry-G/Ask-Eng#9]
The logo must look professional since it represents the brand we are creating.  As much as possible it must be inline with the engineering theme of the website.

**Comment by sharon-ho** [comment]
I'll try to draft up a logo for tomorrow! I have some ideas already.

**Comment by Kerry-G** [comment]
Is the logo in progress?

**Comment by Kerry-G** [comment]
@sharon-ho is the logo in progress? If not, I will do something tonight.

**Comment by sharon-ho** [comment]
@Kerry-G It's almost ready. I'll post it up tonight.

**Comment by sharon-ho** [comment]
![ask-eng](https://user-images.githubusercontent.com/33813045/36180059-d6ee0d96-10ec-11e8-9f73-fc1d8c3cb6fe.png)
